
service: url-shortner-nodejs-aws # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/url_shortener__long_urls"


functions:
  getLink:
    handler: handler.getLink
    events:
      - http:
          path: link
          method: post
          cors: true

  getUrl:
    handler: handler.getUrl
    events:
      - http:
          path: /{url}
          method: get
          cors: true
          request:
              parameters:
                  paths:
                      url: true

resources:
  Resources:
    urlShortener:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: shortUrl
            AttributeType: S
        KeySchema:
          -
            AttributeName: shortUrl
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: url_shortener__long_urls

custom:
  customDomain:
    domainName: '*.tiny.tikal.io'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

